openapi: 3.0.3
info:
  title: EXO 1
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /ping:
    get:
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong