openapi: 3.0.3
info:
  title: EXO 2
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /users:
    get:
      parameters:
        - name: page
          in: query
          schema: 
            type: integer
        - name: size
          in: query
          schema:
            type: integer
      responses:
        200:
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                      format: email
        400:
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"




