openapi: 3.0.3
info:
  title: EXO 3
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /tasks:
    get:
      responses:
        200:
          description: Array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'

      responses:
        201:
          description: New array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    delete:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items: 
                type: integer
      responses:
        200:
          description: List of tasks deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Tasks ID
      responses:
        200:
          description: Tasks found
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Task'
        404:
          description: Tasks not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task not found"
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Tasks ID
      responses:
        200:
          description: Tasks deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
    